# Generated by Django 3.2.10 on 2022-01-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFrom', models.CharField(choices=[('upload', 'upload'), ('url', 'url')], max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('imageURL', models.URLField()),
                ('cropType', models.CharField(choices=[('corner', 'corner'), ('center', 'center')], max_length=100)),
                ('isAddGradient', models.BooleanField(default=True)),
                ('isAddBranding', models.BooleanField(default=True)),
                ('isAddTitleText', models.BooleanField(default=True)),
                ('titleTextPosition', models.CharField(choices=[('top', 'top'), ('center', 'center'), ('bottom', 'bottom')], max_length=100)),
                ('titleTextAlignment', models.CharField(choices=[('justified', 'justified'), ('center', 'center'), ('leftAlign', 'leftAlign')], max_length=100)),
                ('isContainImportantWords', models.BooleanField(default=True)),
                ('savedFilename', models.CharField(max_length=100)),
            ],
        ),
    ]
